<script setup>
import { onMounted, onUnmounted, ref } from 'vue'
import { supabase } from './lib/supabase'
const requests = ref([]), loading = ref(true), channel = ref()
async function load(){ if(supabase){ const {data}=await supabase.from('requests').select('*').order('created_at',{ascending:false}); requests.value=data||[] } loading.value=false }
async function updateStatus(request,status){ await supabase?.from('requests').update({status}).eq('id',request.id); request.status=status }
onMounted(async()=>{ await load(); if(supabase) channel.value=supabase.channel('new-requests').on('postgres_changes',{event:'INSERT',schema:'public',table:'requests'},p=>requests.value.unshift(p.new)).subscribe() })
onUnmounted(()=>supabase?.removeChannel(channel.value))
</script>
<template><main class="admin"><header><a class="brand" href="/">atelier<span>print</span><b>.</b></a><div class="live"><i></i> Demandes en direct</div></header><section><p class="eyebrow">ESPACE ADMINISTRATEUR</p><h1>Bonjour, l’atelier<br>est en mouvement.</h1><div class="stats"><div><b>{{requests.length}}</b><span>Nouvelles demandes</span></div><div><b>{{requests.filter(r=>r.status==='in_progress').length}}</b><span>En production</span></div><div><b>{{requests.filter(r=>r.status==='done').length}}</b><span>Terminées</span></div></div><p v-if="loading">Chargement des demandes…</p><div v-else class="request-list"><article v-for="request in requests" :key="request.id"><div><span class="tag">{{request.status || 'new'}}</span><h2>{{request.first_name}} {{request.last_name}}</h2><p>{{request.service}} <b v-if="request.service_option">· {{request.service_option}}</b> · {{request.phone}}</p></div><div><small>{{new Date(request.created_at).toLocaleDateString('fr-FR')}}</small><select :value="request.status" @change="updateStatus(request,$event.target.value)"><option value="new">Nouveau</option><option value="in_progress">En cours</option><option value="done">Terminé</option></select></div></article><p v-if="!requests.length" class="empty">Aucune demande pour le moment. Les nouvelles demandes apparaîtront ici instantanément.</p></div></section></main></template>
<style scoped>.admin{min-height:100vh;background:#f6f2ea;color:#17291f}.admin header{background:#17291f;color:#fff;border:0}.admin .brand{color:white}.admin .brand span{font-family:inherit;font-style:normal}.admin .brand b{color:#d8ff4e}.live{font:11px 'DM Mono';letter-spacing:1px}.live i{display:inline-block;width:8px;height:8px;background:#d8ff4e;border-radius:100%;margin-right:6px}.admin section{padding:70px 9%;max-width:1250px;margin:auto}.admin h1{font-size:clamp(42px,6vw,82px);letter-spacing:-4px;line-height:.96;margin:0 0 55px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:45px}.stats div{padding:25px;background:#dce8cf}.stats b{display:block;font-size:38px}.stats span{font-size:12px}.request-list{border-top:1px solid #c7c8bd}.request-list article{padding:19px 0;border-bottom:1px solid #c7c8bd;display:flex;align-items:center;justify-content:space-between}.request-list h2{font-size:18px;margin:8px 0}.request-list p{font-size:12px;margin:0;color:#586458}.request-list article>div:last-child{text-align:right;display:grid;gap:8px}.request-list small{font-size:10px}.request-list select{font-size:11px;padding:6px}.tag{font:9px 'DM Mono';letter-spacing:1px;background:#d8ff4e;padding:4px 6px}.empty{padding:40px 0;color:#586458}@media(max-width:600px){.stats{grid-template-columns:1fr}.request-list article{align-items:flex-start;gap:10px}.admin section{padding:50px 6%}}</style>
